[database]
url = "localhost"
port = 5432
user = "postgres"
password = "postgres"
database = "generationApp"
[clip]
engine = "ort"
model = "app/model/weights/clip.onnx"
output = ["LOGITS_PER_IMAGE", "LOGITS_PER_TEXT"]

[background]
engine = "ort"
model = "app/model/weights/remover.onnx"

[inpainting]
engine = "torch"

[gpt]
engine = "torch"